# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded WS::Client 1.1.2 [list source [file join $dir ClientSide.tcl]]
package ifneeded WS::Server 1.1.2 [list source [file join $dir ServerSide.tcl]]
package ifneeded WS::Utils 1.1.2 [list source [file join $dir Utilities.tcl]]
package ifneeded WS::Embeded 1.1.2 [list source [file join $dir Embedded.tcl]]
