package ifneeded WS::AOLserver 2.5.0 [list source [file join $dir AOLserver.tcl]]
package ifneeded WS::Channel 2.5.0 [list source [file join $dir ChannelServer.tcl]]
package ifneeded WS::Client 3.1.0 [list source [file join $dir ClientSide.tcl]]
package ifneeded WS::Embeded 3.4.0 [list source [file join $dir Embedded.tcl]]
package ifneeded WS::Server 3.5.0 [list source [file join $dir ServerSide.tcl]]
package ifneeded WS::Utils 3.2.0 [list source [file join $dir Utilities.tcl]]
package ifneeded WS::Wub 2.5.0 [list source [file join $dir WubServer.tcl]]
package ifneeded Wsdl 2.4.0 [list source [file join $dir WubServer.tcl]]
